# Generated by Django 6.0.4 on 2026-05-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_curso_autor_noticia_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.TextField(verbose_name='Subtítulo')),
                ('etiqueta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta (Ej: NUEVA PLATAFORMA)')),
                ('imagen_fondo', models.ImageField(upload_to='carrusel/', verbose_name='Imagen de Fondo')),
                ('enlace_url', models.URLField(blank=True, null=True, verbose_name='Enlace Externo (Opcional)')),
                ('texto_boton', models.CharField(default='Ver Detalles', max_length=50, verbose_name='Texto del Botón')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo (Mostrar en inicio)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('curso_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides_carrusel', to='app.curso', verbose_name='Curso Vinculado')),
                ('noticia_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides_carrusel', to='app.noticia', verbose_name='Noticia Vinculada')),
            ],
            options={
                'verbose_name': 'Diapositiva del Carrusel',
                'verbose_name_plural': 'Carrusel Principal',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
