# Generated by Django 6.0.4 on 2026-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carrusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='vistas',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas'),
        ),
    ]
