# Generated by Django 6.0.4 on 2026-05-11 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_noticia_vistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Completado')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='app.modulo', verbose_name='Módulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_modulos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Módulo',
                'verbose_name_plural': 'Progreso de Módulos',
                'ordering': ['fecha_completado'],
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
