# Generated by Django 6.0.3 on 2026-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_progresomodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='es_evaluable',
            field=models.BooleanField(default=False, help_text='Si se marca, el usuario no podrá completarlo manualmente; dependerá de la validación del administrador.', verbose_name='Es actividad evaluable'),
        ),
        migrations.AddField(
            model_name='progresomodulo',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='progresomodulo',
            name='estado',
            field=models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('calificado', 'Calificado')], default='completado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='progresomodulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='progresomodulo',
            name='retroalimentacion',
            field=models.TextField(blank=True, verbose_name='Retroalimentación/Observaciones'),
        ),
        migrations.AlterField(
            model_name='progresomodulo',
            name='fecha_completado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
