# Generated by Django 6.0.3 on 2026-06-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='enlace_drive',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace a Google Drive u otro servicio donde esté alojada la actividad o el documento.', null=True, verbose_name='Enlace de Drive (Actividad)'),
        ),
    ]
