# Generated by Django 6.0.3 on 2026-06-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_modulo_enlace_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='curso_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides_carrusel', to='app.curso', verbose_name='Curso Vinculado'),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='noticia_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides_carrusel', to='app.noticia', verbose_name='Noticia Vinculada'),
        ),
    ]
