# Generated by Django 6.0.3 on 2026-06-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_carrusel_curso_vinculado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='video_url_2',
            field=models.URLField(blank=True, help_text='Enlace opcional para un segundo video de YouTube.', null=True, verbose_name='URL de Video 2 (YouTube)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='video_url_3',
            field=models.URLField(blank=True, help_text='Enlace opcional para un tercer video de YouTube.', null=True, verbose_name='URL de Video 3 (YouTube)'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace del video de YouTube para embeber.', null=True, verbose_name='URL de Video 1 (YouTube)'),
        ),
    ]
